#!/bin/bash

SEREBII_INFIX=$1
OUT_SUFFIX=$2

mkdir -p scripts/scraped_$OUT_SUFFIX

for ((i=152;i<=251;i++)); do
    url="http://www.serebii.net/$SEREBII_INFIX/`printf %03d $i`.png"
    echo "getting $url"
    wget -O "scripts/scraped_$OUT_SUFFIX/`printf %03d $i`.png" $url
done
